List<Map<String, String>> currencyCountryDropdown = [
  {'currency': 'USD', 'country': 'US', 'name': 'United States'},
  {'currency': 'AED', 'country': 'AE', 'name': 'United Arab Emirates'},
  {'currency': 'AFN', 'country': 'AF', 'name': 'Afghanistan'},
  {'currency': 'ALL', 'country': 'AL', 'name': 'Albania'},
  {'currency': 'AMD', 'country': 'AM', 'name': 'Armenia'},
  {'currency': 'ANG', 'country': 'AN', 'name': 'Netherlands Antilles'},
  {'currency': 'AOA', 'country': 'AO', 'name': 'Angola'},
  {'currency': 'ARS', 'country': 'AR', 'name': 'Argentina'},
  {'currency': 'AUD', 'country': 'AU', 'name': 'Australia'},
  {'currency': 'AWG', 'country': 'AW', 'name': 'Aruba'},
  {'currency': 'AZN', 'country': 'AZ', 'name': 'Azerbaijan'},
  {'currency': 'BAM', 'country': 'BA', 'name': 'Bosnia and Herzegovina'},
  {'currency': 'BBD', 'country': 'BB', 'name': 'Barbados'},
  {'currency': 'BDT', 'country': 'BD', 'name': 'Bangladesh'},
  {'currency': 'BGN', 'country': 'BG', 'name': 'Bulgaria'},
  {'currency': 'BHD', 'country': 'BH', 'name': 'Bahrain'},
  {'currency': 'BIF', 'country': 'BI', 'name': 'Burundi'},
  {'currency': 'BMD', 'country': 'BM', 'name': 'Bermuda'},
  {'currency': 'BND', 'country': 'BN', 'name': 'Brunei Darussalam'},
  {'currency': 'BOB', 'country': 'BO', 'name': 'Bolivia'},
  {'currency': 'BRL', 'country': 'BR', 'name': 'Brazil'},
  {'currency': 'BSD', 'country': 'BS', 'name': 'Bahamas'},
  {'currency': 'BTN', 'country': 'BT', 'name': 'Bhutan'},
  {'currency': 'BWP', 'country': 'BW', 'name': 'Botswana'},
  {'currency': 'BYN', 'country': 'BY', 'name': 'Belarus'},
  {'currency': 'BZD', 'country': 'BZ', 'name': 'Belize'},
  {'currency': 'CAD', 'country': 'CA', 'name': 'Canada'},
  {
    'currency': 'CDF',
    'country': 'CD',
    'name': 'Democratic Republic of the Congo'
  },
  {'currency': 'CHF', 'country': 'CH', 'name': 'Switzerland'},
  {'currency': 'CLP', 'country': 'CL', 'name': 'Chile'},
  {'currency': 'CNY', 'country': 'CN', 'name': 'China'},
  {'currency': 'COP', 'country': 'CO', 'name': 'Colombia'},
  {'currency': 'CRC', 'country': 'CR', 'name': 'Costa Rica'},
  {'currency': 'CUP', 'country': 'CU', 'name': 'Cuba'},
  {'currency': 'CVE', 'country': 'CV', 'name': 'Cape Verde'},
  {'currency': 'CZK', 'country': 'CZ', 'name': 'Czech Republic'},
  {'currency': 'DJF', 'country': 'DJ', 'name': 'Djibouti'},
  {'currency': 'DKK', 'country': 'DK', 'name': 'Denmark'},
  {'currency': 'DOP', 'country': 'DO', 'name': 'Dominican Republic'},
  {'currency': 'DZD', 'country': 'DZ', 'name': 'Algeria'},
  {'currency': 'EGP', 'country': 'EG', 'name': 'Egypt'},
  {'currency': 'ERN', 'country': 'ER', 'name': 'Eritrea'},
  {'currency': 'ETB', 'country': 'ET', 'name': 'Ethiopia'},
  {'currency': 'EUR', 'country': 'EU', 'name': 'Eurozone'},
  {'currency': 'FJD', 'country': 'FJ', 'name': 'Fiji'},
  {'currency': 'FKP', 'country': 'FK', 'name': 'Falkland Islands'},
  {'currency': 'GBP', 'country': 'GB', 'name': 'United Kingdom'},
  {'currency': 'GEL', 'country': 'GE', 'name': 'Georgia'},
  {'currency': 'GHS', 'country': 'GH', 'name': 'Ghana'},
  {'currency': 'GIP', 'country': 'GI', 'name': 'Gibraltar'},
  {'currency': 'GMD', 'country': 'GM', 'name': 'Gambia'},
  {'currency': 'GNF', 'country': 'GN', 'name': 'Guinea'},
  {'currency': 'GTQ', 'country': 'GT', 'name': 'Guatemala'},
  {'currency': 'GYD', 'country': 'GY', 'name': 'Guyana'},
  {'currency': 'HKD', 'country': 'HK', 'name': 'Hong Kong'},
  {'currency': 'HNL', 'country': 'HN', 'name': 'Honduras'},
  {'currency': 'HRK', 'country': 'HR', 'name': 'Croatia'},
  {'currency': 'HTG', 'country': 'HT', 'name': 'Haiti'},
  {'currency': 'HUF', 'country': 'HU', 'name': 'Hungary'},
  {'currency': 'IDR', 'country': 'ID', 'name': 'Indonesia'},
  {'currency': 'ILS', 'country': 'IL', 'name': 'Israel'},
  {'currency': 'IMP', 'country': 'IM', 'name': 'Isle of Man'},
  {'currency': 'INR', 'country': 'IN', 'name': 'India'},
  {'currency': 'IQD', 'country': 'IQ', 'name': 'Iraq'},
  {'currency': 'IRR', 'country': 'IR', 'name': 'Iran'},
  {'currency': 'ISK', 'country': 'IS', 'name': 'Iceland'},
  {'currency': 'JEP', 'country': 'JE', 'name': 'Jersey'},
  {'currency': 'JMD', 'country': 'JM', 'name': 'Jamaica'},
  {'currency': 'JOD', 'country': 'JO', 'name': 'Jordan'},
  {'currency': 'JPY', 'country': 'JP', 'name': 'Japan'},
  {'currency': 'KES', 'country': 'KE', 'name': 'Kenya'},
  {'currency': 'KGS', 'country': 'KG', 'name': 'Kyrgyzstan'},
  {'currency': 'KHR', 'country': 'KH', 'name': 'Cambodia'},
  {'currency': 'KID', 'country': 'KI', 'name': 'Kiribati'},
  {'currency': 'KMF', 'country': 'KM', 'name': 'Comoros'},
  {'currency': 'KRW', 'country': 'KR', 'name': 'South Korea'},
  {'currency': 'KWD', 'country': 'KW', 'name': 'Kuwait'},
  {'currency': 'KYD', 'country': 'KY', 'name': 'Cayman Islands'},
  {'currency': 'KZT', 'country': 'KZ', 'name': 'Kazakhstan'},
  {'currency': 'LAK', 'country': 'LA', 'name': 'Laos'},
  {'currency': 'LBP', 'country': 'LB', 'name': 'Lebanon'},
  {'currency': 'LKR', 'country': 'LK', 'name': 'Sri Lanka'},
  {'currency': 'LRD', 'country': 'LR', 'name': 'Liberia'},
  {'currency': 'LSL', 'country': 'LS', 'name': 'Lesotho'},
  {'currency': 'LYD', 'country': 'LY', 'name': 'Libya'},
  {'currency': 'MAD', 'country': 'MA', 'name': 'Morocco'},
  {'currency': 'MDL', 'country': 'MD', 'name': 'Moldova'},
  {'currency': 'MGA', 'country': 'MG', 'name': 'Madagascar'},
  {'currency': 'MKD', 'country': 'MK', 'name': 'North Macedonia'},
  {'currency': 'MMK', 'country': 'MM', 'name': 'Myanmar'},
  {'currency': 'MNT', 'country': 'MN', 'name': 'Mongolia'},
  {'currency': 'MOP', 'country': 'MO', 'name': 'Macau'},
  {'currency': 'MRU', 'country': 'MR', 'name': 'Mauritania'},
  {'currency': 'MUR', 'country': 'MU', 'name': 'Mauritius'},
  {'currency': 'MVR', 'country': 'MV', 'name': 'Maldives'},
  {'currency': 'MWK', 'country': 'MW', 'name': 'Malawi'},
  {'currency': 'MXN', 'country': 'MX', 'name': 'Mexico'},
  {'currency': 'MYR', 'country': 'MY', 'name': 'Malaysia'},
  {'currency': 'MZN', 'country': 'MZ', 'name': 'Mozambique'},
  {'currency': 'NAD', 'country': 'NA', 'name': 'Namibia'},
  {'currency': 'NGN', 'country': 'NG', 'name': 'Nigeria'},
  {'currency': 'NIO', 'country': 'NI', 'name': 'Nicaragua'},
  {'currency': 'NOK', 'country': 'NO', 'name': 'Norway'},
  {'currency': 'NPR', 'country': 'NP', 'name': 'Nepal'},
  {'currency': 'NZD', 'country': 'NZ', 'name': 'New Zealand'},
  {'currency': 'OMR', 'country': 'OM', 'name': 'Oman'},
  {'currency': 'PAB', 'country': 'PA', 'name': 'Panama'},
  {'currency': 'PEN', 'country': 'PE', 'name': 'Peru'},
  {'currency': 'PGK', 'country': 'PG', 'name': 'Papua New Guinea'},
  {'currency': 'PHP', 'country': 'PH', 'name': 'Philippines'},
  {'currency': 'PKR', 'country': 'PK', 'name': 'Pakistan'},
  {'currency': 'PLN', 'country': 'PL', 'name': 'Poland'},
  {'currency': 'PYG', 'country': 'PY', 'name': 'Paraguay'},
  {'currency': 'QAR', 'country': 'QA', 'name': 'Qatar'},
  {'currency': 'RON', 'country': 'RO', 'name': 'Romania'},
  {'currency': 'RSD', 'country': 'RS', 'name': 'Serbia'},
  {'currency': 'RUB', 'country': 'RU', 'name': 'Russia'},
  {'currency': 'RWF', 'country': 'RW', 'name': 'Rwanda'},
  {'currency': 'SAR', 'country': 'SA', 'name': 'Saudi Arabia'},
  {'currency': 'SBD', 'country': 'SB', 'name': 'Solomon Islands'},
  {'currency': 'SCR', 'country': 'SC', 'name': 'Seychelles'},
  {'currency': 'SDG', 'country': 'SD', 'name': 'Sudan'},
  {'currency': 'SEK', 'country': 'SE', 'name': 'Sweden'},
  {'currency': 'SGD', 'country': 'SG', 'name': 'Singapore'},
  {
    'currency': 'SHP',
    'country': 'SH',
    'name': 'Saint Helena, Ascension and Tristan da Cunha'
  },
  {'currency': 'SLE', 'country': 'SL', 'name': 'Sierra Leone'},
  {'currency': 'SLL', 'country': 'SL', 'name': 'Sierra Leone'},
  {'currency': 'SOS', 'country': 'SO', 'name': 'Somalia'},
  {'currency': 'SRD', 'country': 'SR', 'name': 'Suriname'},
  {'currency': 'SSP', 'country': 'SS', 'name': 'South Sudan'},
  {'currency': 'STN', 'country': 'ST', 'name': 'Sao Tome and Principe'},
  {'currency': 'SYP', 'country': 'SY', 'name': 'Syria'},
  {'currency': 'SZL', 'country': 'SZ', 'name': 'Eswatini'},
  {'currency': 'THB', 'country': 'TH', 'name': 'Thailand'},
  {'currency': 'TJS', 'country': 'TJ', 'name': 'Tajikistan'},
  {'currency': 'TMT', 'country': 'TM', 'name': 'Turkmenistan'},
  {'currency': 'TND', 'country': 'TN', 'name': 'Tunisia'},
  {'currency': 'TOP', 'country': 'TO', 'name': 'Tonga'},
  {'currency': 'TRY', 'country': 'TR', 'name': 'Turkey'},
  {'currency': 'TTD', 'country': 'TT', 'name': 'Trinidad and Tobago'},
  {'currency': 'TWD', 'country': 'TW', 'name': 'Taiwan'},
  {'currency': 'TZS', 'country': 'TZ', 'name': 'Tanzania'},
  {'currency': 'UAH', 'country': 'UA', 'name': 'Ukraine'},
  {'currency': 'UGX', 'country': 'UG', 'name': 'Uganda'},
  {'currency': 'UYU', 'country': 'UY', 'name': 'Uruguay'},
  {'currency': 'UZS', 'country': 'UZ', 'name': 'Uzbekistan'},
  {'currency': 'VES', 'country': 'VE', 'name': 'Venezuela'},
  {'currency': 'VND', 'country': 'VN', 'name': 'Vietnam'},
  {'currency': 'VUV', 'country': 'VU', 'name': 'Vanuatu'},
  {'currency': 'WST', 'country': 'WS', 'name': 'Samoa'},
  {'currency': 'XAF', 'country': 'CM', 'name': 'Central African Republic'},
  {'currency': 'XCD', 'country': 'LC', 'name': 'Saint Lucia'},
  {'currency': 'XOF', 'country': 'BJ', 'name': 'Benin'},
  {'currency': 'XPF', 'country': 'PF', 'name': 'French Polynesia'},
  {'currency': 'YER', 'country': 'YE', 'name': 'Yemen'},
  {'currency': 'ZAR', 'country': 'ZA', 'name': 'South Africa'},
  {'currency': 'ZMW', 'country': 'ZM', 'name': 'Zambia'},
  {'currency': 'ZWL', 'country': 'ZW', 'name': 'Zimbabwe'},
];
